In [4]:
import torch
import torchvision
from torchvision import transforms, datasets
import numpy as np
#https://pytorch.org/docs/stable/torch.html - tensor operations practice

In [ ]:
[x1, x2, x3]
employed , graduate, lives in Calgary
[1,0,1]
[0,1,1]


[salary]

50,500, 25100, .....
<20000.1,<30000.1  - 10-20 -> payscales   = >   10:<20,000 : 50: <30, 0000 => 
0, 1, .10000 1 1000 0 





In [5]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
a = torch.empty((2,3))

In [8]:
a

tensor([[1.0682e-05, 1.2973e-11, 1.7663e-04],
        [1.3223e+22, 1.0384e+21, 1.0334e-05]])

In [9]:
#pytorch basics
a = torch.empty(2,3)
b = torch.rand((2,2), dtype=torch.float)
c = torch.ones((2,2), dtype=torch.double)
d = torch.zeros((2,2), dtype=torch.double)
e = torch.zeros((10,2), dtype=torch.float)

In [10]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
b

tensor([[0.3136, 0.3378],
        [0.0762, 0.2141]])

In [12]:
c

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [14]:
a.dtype

torch.float32

In [15]:
b+c

tensor([[1.3136, 1.3378],
        [1.0762, 1.2141]], dtype=torch.float64)

In [16]:
print(e.size())
print(b.size())

torch.Size([10, 2])
torch.Size([2, 2])


In [17]:
e

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
b

tensor([[0.3136, 0.3378],
        [0.0762, 0.2141]])

In [18]:
b[:,0]

tensor([0.3136, 0.0762])

In [20]:
b[0,:]

tensor([0.3136, 0.3378])

In [23]:
b[1,1].item()

0.21410107612609863

In [24]:
n = torch.tensor([2.5,2.4,1.1])

In [25]:
n.dtype

torch.float32

In [26]:
n.size()

torch.Size([3])

In [27]:
n

tensor([2.5000, 2.4000, 1.1000])

In [ ]:
#most tensor operations same as numpy array operations

In [28]:
b

tensor([[0.3136, 0.3378],
        [0.0762, 0.2141]])

In [29]:
#reshape
bflat = b.view(4)

In [30]:
bflat

tensor([0.3136, 0.3378, 0.0762, 0.2141])

In [31]:
print(b.view(1,4))
print(b.view(-1,2))   #figure out the other dimension

tensor([[0.3136, 0.3378, 0.0762, 0.2141]])
tensor([[0.3136, 0.3378],
        [0.0762, 0.2141]])


In [ ]:
blue yellow blue red green
yellow blue(0.1) blue(10) red green
yellow yellow yellow blue 
blue blie blie red green
blue yello blue yellow 




In [ ]:
x1 x2   -  Block
x2, x3
x3, x4
x4

In [33]:
b

tensor([[0.3136, 0.3378],
        [0.0762, 0.2141]])

In [34]:
print(torch.reshape(b, (1, 4)))
print(torch.reshape(b, (-1,1)))

tensor([[0.3136, 0.3378, 0.0762, 0.2141]])
tensor([[0.3136],
        [0.3378],
        [0.0762],
        [0.2141]])


In [35]:
new = torch.rand((10,5))
print(new)
print(new.view((-1,10)))
print(torch.transpose(new, 0, 1))

tensor([[0.6049, 0.3217, 0.4508, 0.6193, 0.5774],
        [0.0655, 0.1959, 0.7764, 0.3019, 0.6418],
        [0.5634, 0.6483, 0.1935, 0.5755, 0.6463],
        [0.5244, 0.2571, 0.9264, 0.0856, 0.4828],
        [0.0089, 0.7649, 0.3337, 0.5647, 0.6815],
        [0.4306, 0.4528, 0.4610, 0.0660, 0.3875],
        [0.4033, 0.6854, 0.6868, 0.5837, 0.4704],
        [0.6616, 0.4008, 0.4453, 0.2065, 0.3912],
        [0.7417, 0.0544, 0.6209, 0.9431, 0.9587],
        [0.8696, 0.0963, 0.3359, 0.3524, 0.5675]])
tensor([[0.6049, 0.3217, 0.4508, 0.6193, 0.5774, 0.0655, 0.1959, 0.7764, 0.3019,
         0.6418],
        [0.5634, 0.6483, 0.1935, 0.5755, 0.6463, 0.5244, 0.2571, 0.9264, 0.0856,
         0.4828],
        [0.0089, 0.7649, 0.3337, 0.5647, 0.6815, 0.4306, 0.4528, 0.4610, 0.0660,
         0.3875],
        [0.4033, 0.6854, 0.6868, 0.5837, 0.4704, 0.6616, 0.4008, 0.4453, 0.2065,
         0.3912],
        [0.7417, 0.0544, 0.6209, 0.9431, 0.9587, 0.8696, 0.0963, 0.3359, 0.3524,
         0.5675]])
ten

In [36]:
new1 = np.random.rand(10,5)
print(new1)
print(np.reshape(new1, (-1,10)))
print(np.transpose(new1))

[[0.58697274 0.98954217 0.60854059 0.90126081 0.08174822]
 [0.99907151 0.25665818 0.71169114 0.13643027 0.83496476]
 [0.13227255 0.18690964 0.58472991 0.07769499 0.07960014]
 [0.90826685 0.73012417 0.64780658 0.17688405 0.89679942]
 [0.65619684 0.41892711 0.63779619 0.30653895 0.31980079]
 [0.90048266 0.91621358 0.02562635 0.51038838 0.41192362]
 [0.96149397 0.38026982 0.48926493 0.47824286 0.66313371]
 [0.34520371 0.48500744 0.72875402 0.84039205 0.20825617]
 [0.62728973 0.23722679 0.699484   0.93584319 0.89173755]
 [0.67354681 0.74539671 0.10403076 0.76189469 0.47401359]]
[[0.58697274 0.98954217 0.60854059 0.90126081 0.08174822 0.99907151
  0.25665818 0.71169114 0.13643027 0.83496476]
 [0.13227255 0.18690964 0.58472991 0.07769499 0.07960014 0.90826685
  0.73012417 0.64780658 0.17688405 0.89679942]
 [0.65619684 0.41892711 0.63779619 0.30653895 0.31980079 0.90048266
  0.91621358 0.02562635 0.51038838 0.41192362]
 [0.96149397 0.38026982 0.48926493 0.47824286 0.66313371 0.34520371
  0.48

In [37]:
x = torch.linspace(3, 10, steps=5)
print(x)
x = np.linspace(3, 10, 5)
print(x)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
[ 3.    4.75  6.5   8.25 10.  ]


In [38]:
torch.logspace(start=-10, end=10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [39]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
torch.full((2, 3), 10)

..\aten\src\ATen\native\TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [1]:
#b.add_(1) #undescores does inplace pointer operations

In [ ]:
#Torch numpy interchangeable - numpy operations on cpu during data manpulation - loaded from file ..
#For easily conversion to Tensors - handy functions

In [43]:
type(b)

torch.Tensor

In [41]:
c = b.numpy() #inplace deep copy (pointer) # modifying one modifies another

In [44]:
type(c)

numpy.ndarray

In [45]:
z = np.ones((3,5))
torch.from_numpy(z)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [46]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones((3,4), device=device)
x = torch.ones((3,4))
y = x.to(device)
#this is a very expensive operation
a = np.array([1, 2, 3])
t = torch.as_tensor(a, device=torch.device('cuda'))

In [47]:
t

tensor([1, 2, 3], device='cuda:0', dtype=torch.int32)

_____

In [49]:
float 32, 64 - > <GPU
int , 64 <<GPU   -> int, 128 -

x = torch.rand(2, 1, 2, 1, 2)
print(x)
print(x.size())

tensor([[[[[0.7041, 0.7640]],

          [[0.7493, 0.8939]]]],



        [[[[0.9879, 0.9504]],

          [[0.8890, 0.8225]]]]])
torch.Size([2, 1, 2, 1, 2])


In [50]:
x = torch.rand(3, 1, 2, 1, 2)
print(x)
print(x.size())
print(x[0].size())
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[0][0][0][0])

tensor([[[[[0.1947, 0.5631]],

          [[0.5524, 0.5973]]]],



        [[[[0.2889, 0.4118]],

          [[0.5598, 0.9114]]]],



        [[[[0.0097, 0.2511]],

          [[0.2388, 0.3082]]]]])
torch.Size([3, 1, 2, 1, 2])
torch.Size([1, 2, 1, 2])
tensor([[[[0.1947, 0.5631]],

         [[0.5524, 0.5973]]]])
tensor([[[0.1947, 0.5631]],

        [[0.5524, 0.5973]]])
tensor([[0.1947, 0.5631]])
tensor([0.1947, 0.5631])


In [51]:
x = torch.rand(3, 2, 3, 2, 3)
print(x)
print(x.size())
print(x[0].size())
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[0][0][0][0])

tensor([[[[[0.6483, 0.1980, 0.9609],
           [0.2241, 0.1855, 0.0703]],

          [[0.8873, 0.9315, 0.0210],
           [0.1664, 0.5324, 0.6830]],

          [[0.1575, 0.6777, 0.7062],
           [0.7432, 0.4603, 0.0042]]],


         [[[0.1151, 0.1472, 0.3498],
           [0.6997, 0.5485, 0.2266]],

          [[0.4920, 0.4458, 0.9442],
           [0.7400, 0.1992, 0.9720]],

          [[0.0834, 0.7722, 0.2784],
           [0.9416, 0.8362, 0.6369]]]],



        [[[[0.6723, 0.3798, 0.2053],
           [0.6875, 0.9429, 0.3572]],

          [[0.4337, 0.5411, 0.1714],
           [0.8670, 0.0367, 0.1718]],

          [[0.2370, 0.6608, 0.9129],
           [0.0886, 0.5372, 0.0971]]],


         [[[0.5860, 0.3129, 0.8105],
           [0.4483, 0.1331, 0.3269]],

          [[0.1924, 0.0898, 0.4257],
           [0.5605, 0.5883, 0.8561]],

          [[0.7988, 0.0118, 0.6087],
           [0.6822, 0.6377, 0.7676]]]],



        [[[[0.5659, 0.0879, 0.6163],
           [0.6891, 0.3637, 0.1536]],



In [52]:
x = torch.rand(2, 1, 2, 1, 2)
print(x.size())
print(x)
print("##################")
y = torch.squeeze(x)
print(y.size())
print(y)
print(y[0])
print(y[0][0])

print("##################")
y = torch.squeeze(x, 0)
print(y.size())
print(y)
print(y[0])
print(y[0][0])
print("##################")
y = torch.squeeze(x, 1)
print(y.size())
print(y)
print(y[0])
print(y[0][0])

torch.Size([2, 1, 2, 1, 2])
tensor([[[[[0.8657, 0.4864]],

          [[0.7230, 0.2550]]]],



        [[[[0.4628, 0.1672]],

          [[0.0824, 0.2315]]]]])
##################
torch.Size([2, 2, 2])
tensor([[[0.8657, 0.4864],
         [0.7230, 0.2550]],

        [[0.4628, 0.1672],
         [0.0824, 0.2315]]])
tensor([[0.8657, 0.4864],
        [0.7230, 0.2550]])
tensor([0.8657, 0.4864])
##################
torch.Size([2, 1, 2, 1, 2])
tensor([[[[[0.8657, 0.4864]],

          [[0.7230, 0.2550]]]],



        [[[[0.4628, 0.1672]],

          [[0.0824, 0.2315]]]]])
tensor([[[[0.8657, 0.4864]],

         [[0.7230, 0.2550]]]])
tensor([[[0.8657, 0.4864]],

        [[0.7230, 0.2550]]])
##################
torch.Size([2, 2, 1, 2])
tensor([[[[0.8657, 0.4864]],

         [[0.7230, 0.2550]]],


        [[[0.4628, 0.1672]],

         [[0.0824, 0.2315]]]])
tensor([[[0.8657, 0.4864]],

        [[0.7230, 0.2550]]])
tensor([[0.8657, 0.4864]])


In [53]:
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))


tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [54]:
x = torch.randn(3, 2, 2)
y = torch.ones(3, 2, 2)
print(x)
print(y)
out = torch.where(x > 0, x, y)
print(out)

tensor([[[ 0.7954, -0.3675],
         [ 0.9377,  1.7704]],

        [[ 1.6999, -0.4509],
         [-0.9554, -0.4467]],

        [[-0.7611,  0.8265],
         [-0.7943,  0.2559]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[[0.7954, 1.0000],
         [0.9377, 1.7704]],

        [[1.6999, 1.0000],
         [1.0000, 1.0000]],

        [[1.0000, 0.8265],
         [1.0000, 0.2559]]])


_______________

###########

In [56]:
x = torch.rand(3, requires_grad=False)
print(x)
#data

tensor([0.0596, 0.7441, 0.3820])


In [61]:
y = torch.rand(3, requires_grad=True)
print(y)
#weights

tensor([0.0965, 0.4672, 0.5187], requires_grad=True)


In [57]:
y = x+2
print(y)
z = x*2
print(z)
t = x*x
print(t)
g = x**x
print(g)
mean = x.mean()
print(mean)

tensor([2.0596, 2.7441, 2.3820])
tensor([0.1193, 1.4881, 0.7640])
tensor([0.0036, 0.5536, 0.1459])
tensor([0.8452, 0.8025, 0.6924])
tensor(0.3952)


In [62]:
 mean= y.mean()
print(mean)
mean.backward()
print(y.grad)

tensor(0.3608, grad_fn=<MeanBackward0>)
tensor([0.3333, 0.3333, 0.3333])


In [ ]:
g.backward(x)
x.grad

In [ ]:
x.requires_grad_(False) #inplace
x.detach()
with torch.no_grad():
    operation....