https://deeplizard.com/learn/video/nyjbcRQ-uQ8

In [1]:
import numpy as np
import time
import random
import gym
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0')

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [81]:
num_episodes = 100000
max_steps_per_episode = 500
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [85]:
num_episodes = 100000
max_steps_per_episode = 500
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.01

In [100]:
num_episodes = 100000
max_steps_per_episode = 50
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.01

In [110]:
num_episodes = 100000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.01

In [111]:
rewards_all_episodes = []

for episode in range(num_episodes):
    
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1-learning_rate)  + (reward + discount_rate*np.max(q_table[new_state, :]))*learning_rate
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)

In [112]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

1000 :  0.5470000000000004
2000 :  0.7260000000000005
3000 :  0.7500000000000006
4000 :  0.7440000000000005
5000 :  0.7130000000000005
6000 :  0.7200000000000005
7000 :  0.7410000000000005
8000 :  0.7550000000000006
9000 :  0.7400000000000005
10000 :  0.7270000000000005
11000 :  0.7220000000000005
12000 :  0.7590000000000006
13000 :  0.7200000000000005
14000 :  0.7010000000000005
15000 :  0.7280000000000005
16000 :  0.7320000000000005
17000 :  0.7400000000000005
18000 :  0.7340000000000005
19000 :  0.7410000000000005
20000 :  0.7250000000000005
21000 :  0.7230000000000005
22000 :  0.7330000000000005
23000 :  0.7160000000000005
24000 :  0.7150000000000005
25000 :  0.7450000000000006
26000 :  0.7070000000000005
27000 :  0.7490000000000006
28000 :  0.7220000000000005
29000 :  0.7100000000000005
30000 :  0.7240000000000005
31000 :  0.7140000000000005
32000 :  0.7420000000000005
33000 :  0.7460000000000006
34000 :  0.7000000000000005
35000 :  0.7480000000000006
36000 :  0.7180000000000005
3

In [113]:
q_table

array([[0.51693959, 0.49820746, 0.49923499, 0.49207861],
       [0.2442638 , 0.30217949, 0.24497658, 0.49552058],
       [0.39014429, 0.41884406, 0.4300983 , 0.46662112],
       [0.27076125, 0.35817194, 0.27957505, 0.4514698 ],
       [0.52992038, 0.4376216 , 0.31140897, 0.31077602],
       [0.        , 0.        , 0.        , 0.        ],
       [0.1314064 , 0.09386407, 0.32595403, 0.1330566 ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.43270191, 0.30484439, 0.39731037, 0.5570082 ],
       [0.39339884, 0.58856007, 0.30221437, 0.37304281],
       [0.58190089, 0.29814845, 0.40076766, 0.35933812],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.45141187, 0.38422231, 0.74548515, 0.44884097],
       [0.73878606, 0.90134464, 0.71446126, 0.73717771],
       [0.        , 0.        , 0.        , 0.        ]])

In [109]:
for episode in range(3):
    state = env.reset()
    done = False
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("Goal reached")
                time.sleep(3)
            else:
                print("Fail")
                time.sleep(3)
            clear_output(wait = True)
            break
            
        state = new_state
        
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG


SARSA

In [114]:
import numpy as np 
import gym 
#Building the environment 
env = gym.make('FrozenLake-v0') 

#Defining the different parameters 
epsilon = 0.9
total_episodes = 10000
max_steps = 100
alpha = 0.85
gamma = 0.95

#Initializing the Q-matrix 
Q = np.zeros((env.observation_space.n, env.action_space.n)) 

#Function to choose the next action 
def choose_action(state): 
	action=0
	if np.random.uniform(0, 1) < epsilon: 
		action = env.action_space.sample() 
	else: 
		action = np.argmax(Q[state, :]) 
	return action 

#Function to learn the Q-value 
def update(state, state2, reward, action, action2): 
	predict = Q[state, action] 
	target = reward + gamma * Q[state2, action2] 
	Q[state, action] = Q[state, action] + alpha * (target - predict) 



In [121]:
#Initializing the reward 
reward=0

# Starting the SARSA learning 
for episode in range(total_episodes): 
    t = 0
    state1 = env.reset() 
    action1 = choose_action(state1) 
    
    while t < max_steps: 
        if t%100 == 0:
            env.render() 
        
        #Getting the next state 
        state2, reward, done, info = env.step(action1) 
    
        #Choosing the next action 
        action2 = choose_action(state2) 
        
        #Learning the Q-value 
        update(state1, state2, reward, action1, action2) 
    
        state1 = state2 
        action1 = action2 
        
        #Updating the respective vaLues 
        t += 1
        reward += 1
        
        #If at the end of learning process 
        if done: 
            break
    
#Evaluating the performance 
print ("Performace : ", reward/total_episodes) 

#Visualizing the Q-matrix 
print(Q) 



SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF


SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FF

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFF